version:  "3"
services:
  web:
    image: nginx:latest
    container_name: dev_nginx
    ports:
      - "8000:80"
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html"
    depends_on:
      - php
      - mysql

  php:
    image: nanoninja/php-fpm
    container_name: dev_php
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./web:/var/www/html"

  mysql:
    image: mariadb:latest
    container_name: dev_mysql
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./db/mysql:/var/lib/mysql"

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_myadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=dev_mysql
    depends_on:
      - mysql
